# -*- coding: utf-8 -*-
"""ImageProject1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yippVeTh7PVEucdtl2pt6COJ-qzUvbuJ
"""

!pip install icrawler

import os
from icrawler.builtin import BingImageCrawler

# 1. Define the exact queries from your Milestone 1 document
pothole_queries = [
    "pothole road asphalt damage",
    "road pothole crater street",
    "damaged road surface pothole",
    "deep pothole highway",
    "pothole urban road repair",
    "road hole pavement crack"
]

debris_queries = [
    "road debris fallen objects highway",
    "construction debris on road",
    "rocks fallen on road",
    "tire fragments road debris",
    "tree branch fallen on highway",
    "cargo spill road blockage",
    "gravel debris road surface"
]

def scrape_hazards(queries, category_name, target_per_query=100):
    """Scrapes images using Bing to bypass Google's blocking."""
    save_dir = f'dataset/{category_name}'
    os.makedirs(save_dir, exist_ok=True)

    # Document requires type=photo and size=large
    filters = dict(type='photo', size='large')

    for query in queries:
        print(f"Scraping for query: '{query}'")
        # Switched to BingImageCrawler here
        crawler = BingImageCrawler(
            storage={'root_dir': save_dir},
            downloader_threads=4
        )

        # file_idx_offset='auto' prevents overwriting existing files
        crawler.crawl(
            keyword=query,
            filters=filters,
            max_num=target_per_query,
            file_idx_offset='auto'
        )

# 2. Execute the scraping
print("Starting Pothole Scraping with Bing...")
scrape_hazards(pothole_queries, 'pothole', target_per_query=100)

print("\nStarting Debris Scraping with Bing...")
scrape_hazards(debris_queries, 'debris', target_per_query=100)

print("\nScraping complete! Check the 'dataset' folder in your Colab files.")

from icrawler.builtin import BaiduImageCrawler

# 1. Fresh, broader queries to find new images
pothole_queries_part2 = [
    "broken asphalt street",
    "large road crater",
    "street surface damage",
    "sinkhole road",
    "pothole damage car",
    "bad road condition"
]

debris_queries_part2 = [
    "trash dumped on road",
    "spilled cargo highway",
    "fallen tree blocking road",
    "accident debris street",
    "rocks mountain road",
    "scattered garbage street"
]

def top_up_dataset(queries, category_name, target_per_query=100):
    save_dir = f'dataset/{category_name}'

    for query in queries:
        print(f"Baidu Scraping: '{query}'")
        # Using Baidu this time as our secondary fallback
        crawler = BaiduImageCrawler(
            storage={'root_dir': save_dir},
            downloader_threads=4
        )
        crawler.crawl(
            keyword=query,
            max_num=target_per_query,
            file_idx_offset='auto'
        )

print("Starting Pothole Top-Up...")
top_up_dataset(pothole_queries_part2, 'pothole', target_per_query=80)

print("\nStarting Debris Top-Up...")
top_up_dataset(debris_queries_part2, 'debris', target_per_query=80)

print("\nTop-up complete!")

import os

pothole_count = len(os.listdir('dataset/pothole'))
debris_count = len(os.listdir('dataset/debris'))

print(f"Total Pothole images: {pothole_count}")
print(f"Total Debris images: {debris_count}")
print(f"Total Dataset size: {pothole_count + debris_count}")

import os
import cv2
import numpy as np
from glob import glob

def preprocess_images(input_dir, output_dir, img_size=(128, 128)):
    print(f"Reading raw images from '{input_dir}'...")
    os.makedirs(output_dir, exist_ok=True)

    # Setup CLAHE (Contrast Limited Adaptive Histogram Equalization)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))

    # Setup a standard sharpening kernel
    sharpen_kernel = np.array([[-1,-1,-1],
                               [-1, 9,-1],
                               [-1,-1,-1]])

    # Grab all files in the subdirectories
    filepaths = glob(os.path.join(input_dir, "*", "*.*"))
    processed_count = 0

    for filepath in filepaths:
        try:
            # 1. Read image directly in grayscale
            img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)

            # Skip if the file wasn't a valid image file
            if img is None:
                continue

            # 2. Resize strictly to 128x128 as defined in the project brief
            img_resized = cv2.resize(img, img_size)

            # 3. Noise removal via Gaussian Blur
            img_blurred = cv2.GaussianBlur(img_resized, (3, 3), 0)

            # 4. Apply CLAHE for histogram equalization
            img_clahe = clahe.apply(img_blurred)

            # 5. Apply Sharpening kernel
            img_sharpened = cv2.filter2D(img_clahe, -1, sharpen_kernel)

            # Determine class folder (pothole or debris)
            class_name = os.path.basename(os.path.dirname(filepath))
            save_dir = os.path.join(output_dir, class_name)
            os.makedirs(save_dir, exist_ok=True)

            # Save the processed image
            filename = os.path.basename(filepath)
            save_path = os.path.join(save_dir, f"pre_{filename}")

            # Write to disk
            cv2.imwrite(save_path, img_sharpened)
            processed_count += 1

        except Exception as e:
            # Silently handle any corrupted image files from the web scraper
            pass

    print(f"Success! Preprocessed {processed_count} valid images and saved them to '{output_dir}'.")

# Execute Step 2
preprocess_images(input_dir='dataset', output_dir='dataset_preprocessed', img_size=(128, 128))

import os
import cv2
import numpy as np
from skimage.feature import hog
from glob import glob

def extract_hog_features(input_dir):
    print(f"Extracting HOG features from '{input_dir}'...")

    features = []
    labels = []

    # Class mapping as defined in the problem statement
    # Class 0: Pothole, Class 1: Debris
    class_mapping = {'pothole': 0, 'debris': 1}

    # Grab all our preprocessed images
    filepaths = glob(os.path.join(input_dir, "*", "pre_*"))
    processed_count = 0

    for filepath in filepaths:
        # Read the preprocessed image in grayscale
        img = cv2.imread(filepath, cv2.IMREAD_GRAYSCALE)
        if img is None:
            continue

        # Figure out if this is a pothole or debris based on the folder name
        class_name = os.path.basename(os.path.dirname(filepath))
        label = class_mapping.get(class_name)

        if label is None:
            continue

        # Extract HOG using the STRICT parameters from the project brief
        fd = hog(img,
                 orientations=9,
                 pixels_per_cell=(16, 16),
                 cells_per_block=(2, 2),
                 block_norm='L2-Hys',
                 visualize=False,
                 feature_vector=True)

        features.append(fd)
        labels.append(label)
        processed_count += 1

    # Convert lists to NumPy arrays for scikit-learn
    X = np.array(features)
    y = np.array(labels)

    print(f"Extraction complete! Processed {processed_count} images.")
    print(f"Feature matrix shape (X): {X.shape}")
    print(f"Labels shape (y): {y.shape}")

    return X, y

# Execute Step 3
X, y = extract_hog_features('dataset_preprocessed')

# Verify the 1,764 dimensions requirement

import os
import joblib
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline

# 1. Stratified Train/Test Split (80/20)
print("Splitting data into 80% training and 20% testing...")
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print(f"Training set: {X_train.shape[0]} images")
print(f"Testing set: {X_test.shape[0]} images")

# 2. Build the Pipeline
# Chains the StandardScaler directly into the SVM
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(kernel='rbf', probability=True, random_state=42))
])

# 3. Setup GridSearchCV for Hyperparameter Tuning
# We test different values of C (regularization) and gamma (kernel width)
param_grid = {
    'svm__C': [0.1, 1, 10],
    'svm__gamma': ['scale', 'auto', 0.01, 0.1]
}

print("\nStarting GridSearchCV for Hyperparameter Tuning...")

# cv=5 uses 5-fold cross-validation
# scoring='f1_weighted' targets the primary metric defined in your document
grid_search = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring='f1_weighted',
    n_jobs=-1,
    verbose=1
)

# 4. Train the model
grid_search.fit(X_train, y_train)

print(f"\nBest Parameters found: {grid_search.best_params_}")
print(f"Best Cross-Validation F1-Score: {grid_search.best_score_:.4f}")

# 5. Save the trained pipeline
best_model = grid_search.best_estimator_
os.makedirs('models', exist_ok=True)
joblib.dump(best_model, 'models/roadguard_svm_pipeline.pkl')

print("\nSUCCESS: Model trained and saved to 'models/roadguard_svm_pipeline.pkl'!")

from sklearn.metrics import classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Predict on the test set
print("Running predictions on the 20% test set...")
y_pred = best_model.predict(X_test)
# Get probabilities for the positive class (Debris = 1) for ROC-AUC
y_proba = best_model.predict_proba(X_test)[:, 1]

# 2. Calculate strictly required metrics from the document
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average='weighted')
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
roc_auc = roc_auc_score(y_test, y_proba)

print("\n--- Milestone 1 Evaluation Metrics ---")
print(f"Accuracy:             {accuracy * 100:.2f}%")
print(f"F1-Score (Weighted):  {f1:.4f}")
print(f"Precision (Weighted): {precision:.4f}")
print(f"Recall (Weighted):    {recall:.4f}")
print(f"ROC-AUC:              {roc_auc:.4f}")
print("--------------------------------------\n")

# 3. Generate Visualizations for EDA Notebook
fig, axes = plt.subplots(1, 2, figsize=(12, 5))

# Plot Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[0],
            xticklabels=['Pothole (0)', 'Debris (1)'],
            yticklabels=['Pothole (0)', 'Debris (1)'])
axes[0].set_title('Confusion Matrix')
axes[0].set_ylabel('Actual Label')
axes[0].set_xlabel('Predicted Label')

# Plot ROC Curve
fpr, tpr, _ = roc_curve(y_test, y_proba)
axes[1].plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
axes[1].plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
axes[1].set_title('Receiver Operating Characteristic (ROC)')
axes[1].set_xlabel('False Positive Rate')
axes[1].set_ylabel('True Positive Rate')
axes[1].legend(loc="lower right")

plt.tight_layout()
plt.show()

import os
import cv2
import numpy as np
import joblib
from skimage.feature import hog
import matplotlib.pyplot as plt

def run_single_inference(image_path, model_path='models/roadguard_svm_pipeline.pkl'):
    """Processes a single image and prints out class and confidence scores."""
    if not os.path.exists(image_path):
        print(f"Error: Image path '{image_path}' does not exist.")
        return

    # 1. Load the trained model pipeline
    model = joblib.load(model_path)

    # 2. Replicate the strict Preprocessing Pipeline from Step 2
    img_raw = cv2.imread(image_path)
    img_gray = cv2.cvtColor(img_raw, cv2.COLOR_BGR2GRAY)
    img_resized = cv2.resize(img_gray, (128, 128))
    img_blurred = cv2.GaussianBlur(img_resized, (3, 3), 0)

    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    img_clahe = clahe.apply(img_blurred)

    sharpen_kernel = np.array([[-1,-1,-1], [-1, 9,-1], [-1,-1,-1]])
    img_preprocessed = cv2.filter2D(img_clahe, -1, sharpen_kernel)

    # 3. Replicate HOG Feature Extraction parameters from Step 3
    fd = hog(img_preprocessed,
             orientations=9,
             pixels_per_cell=(16, 16),
             cells_per_block=(2, 2),
             block_norm='L2-Hys',
             visualize=False,
             feature_vector=True).reshape(1, -1) # Reshape for single prediction

    # 4. Run prediction and probability score estimation
    pred_class_idx = model.predict(fd)[0]
    probabilities = model.predict_proba(fd)[0]

    # Class mapping setup
    classes = {0: 'POTHOLE', 1: 'DEBRIS'}
    prediction_text = classes[pred_class_idx]
    confidence = probabilities[pred_class_idx] * 100

    # Print clean formatted CLI output exactly as requested
    print(f"Image      : {os.path.basename(image_path)}")
    print(f"Prediction : {prediction_text}")
    print(f"Confidence : {confidence:.1f}%")
    print(f"Proba      : {{pothole: {probabilities[0]*100:.1f}%, debris: {probabilities[1]*100:.1f}%}}\n")

    # Simple plot visualizer
    plt.figure(figsize=(4, 4))
    plt.imshow(cv2.cvtColor(img_raw, cv2.COLOR_BGR2RGB))
    plt.title(f"{prediction_text} ({confidence:.1f}%)")
    plt.axis('off')
    plt.show()

def run_batch_inference(folder_path, model_path='models/roadguard_svm_pipeline.pkl'):
    """Processes a directory of image files and generates a summary breakdown."""
    if not os.path.exists(folder_path):
        print(f"Error: Folder path '{folder_path}' does not exist.")
        return

    model = joblib.load(model_path)
    classes = {0: 'POTHOLE', 1: 'DEBRIS'}

    # Supported web and camera extensions
    valid_extensions = ('.jpg', '.jpeg', '.png', '.bmp')
    files = [f for f in os.listdir(folder_path) if f.lower().endswith(valid_extensions)]

    pothole_count = 0
    debris_count = 0

    print(f"Starting batch prediction processing on folder: '{folder_path}'")
    print("-" * 50)

    for filename in files:
        full_path = os.path.join(folder_path, filename)
        try:
            # Quick preprocessing and feature extraction loop
            img = cv2.imread(full_path, cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, (128, 128))
            img = cv2.GaussianBlur(img, (3, 3), 0)
            img = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8)).apply(img)
            img = cv2.filter2D(img, -1, np.array([[-1,-1,-1], [-1, 9,-1], [-1,-1,-1]]))

            fd = hog(img, orientations=9, pixels_per_cell=(16, 16),
                     cells_per_block=(2, 2), block_norm='L2-Hys',
                     visualize=False, feature_vector=True).reshape(1, -1)

            pred_idx = model.predict(fd)[0]
            conf = model.predict_proba(fd)[0][pred_idx] * 100

            print(f"{filename} → {classes[pred_idx]} ({conf:.1f}%)")

            if pred_idx == 0:
                pothole_count += 1
            else:
                debris_count += 1
        except Exception:
            pass

    print("-" * 50)
    print(f"Summary: {pothole_count} potholes | {debris_count} debris | {len(files)} total processed")

# Look inside your raw dataset folder and grab the first file
sample_pothole_dir = 'dataset/pothole'
sample_file = os.listdir(sample_pothole_dir)[5] # Grab the 5th file as a test
sample_path = os.path.join(sample_pothole_dir, sample_file)

# Run it!
run_single_inference(sample_path)